# Experience/To-do/Relationship/Goal
from flask import request, jsonify
from flask_restful import Resource
import cohere
from collections import defaultdict
import datetime


co = cohere.Client("pCuvBtCMTy7LNURTBjKmtx5pdzRADG8mqsnCNakx")
from cohere.responses.classify import Example
categories = ["Positive", "Neutral", "Negative"]
types = ["Experience", "Goal", "Relationship", "Todo"]
examples = [
    Example("I want to quit smoking and lead a tobacco-free life.", "Goal"), 
    Example("I aim to land a job at a prestigious company like Citadel.", "Goal"), 
    Example("I wish to learn to dance and become proficient in a specific style, such as salsa or hip-hop.", "Goal"), 
    Example("I dream of traveling to at least three different continents.", "Goal"), 
    Example("I'm saving up for my dream vacation to a specific destination.", "Goal"), 
    Example("I hope to find a life partner and build a loving, long-term relationship.", "Goal"), 
    Example("I'm determined to get in shape and achieve a healthy body weight.", "Goal"), 
    Example("I want to learn to play a musical instrument, like the piano or guitar.", "Goal"), 
     Example("I need to start coming to class early.", "Goal"), 
    Example("I'm passionate about mastering a challenging hobby, such as rock climbing or photography.", "Goal"),
     Example("I plan to start a family and have children.", "Goal"), 
     Example("I aim to become a skilled public speaker and overcome stage fright.", "Goal"), 
     Example("I'm working on launching a successful online business or e-commerce store.", "Goal"), 
     Example("I aspire to write a novel or screenplay.", "Goal"), 
     Example("I want to become fluent in sign language to enhance communication.", "Goal"), 
     Example("I need to change the way I act.", "Goal"), 
     Example("I plan to volunteer regularly at a local animal shelter or food bank.", "Goal"), 
     Example("I'm committed to improving my culinary skills and cooking gourmet meals at home.", "Goal"), 
     Example("I'm determined to complete a challenging physical feat, like running a marathon or hiking a famous trail.", "Goal"), 
     Example("I'm striving to achieve a work-life balance that allows for more leisure and personal time.", "Goal"), 
     Example("I'm working on developing a mindfulness and meditation practice for stress reduction.", "Goal"), 
     Example("I'm building a collection of rare or valuable items, such as vintage cars or rare books.", "Goal"), 
     Example("I aim to become financially independent and secure my future.", "Goal"), 
     Example("I want to earn a master's degree in my field of interest.", "Goal"), 
     Example("I wish to learn a new language and become proficient in it.", "Goal"), 
     Example("I will be a more effective communicator", "Goal"), 
     Example("I'm determined to overcome my fear of public speaking.", "Goal"), 
     Example("I hope to travel to specific countries I've always dreamed of visiting.", "Goal"), 
     Example("I want to save enough money for a down payment on a house.", "Goal"), 
     Example("I need to improve my time management and productivity skills.", "Goal"), 
     Example("I plan to start a nonprofit organization to support a cause I'm passionate about.", "Goal"), 
     Example("I aspire to become a recognized expert in my industry.", "Goal"), 
     Example("I'm working on improving my physical fitness and achieving specific fitness goals.", "Goal"), 
     Example("I want to build a strong social network and make new friends.", "Goal"), 
     Example("I aim to become a mentor and help others achieve their goals.", "Goal"), 
     Example("I wish to learn a new skill, such as coding or graphic design.", "Goal"), 
     Example("I dream of achieving a better work-life balance.", "Goal"), 
     Example("I'm committed to reducing my carbon footprint and living a more sustainable life.", "Goal"),
      Example("I want to develop my creativity and pursue artistic endeavors.", "Goal"), 
      Example("I plan to pay off all my outstanding debts and become debt-free.", "Goal"), 
      Example("I aspire to become a better listener and communicator in my relationships.", "Goal"), 
      Example("I aim to take on new challenges and step out of my comfort zone.", "Goal"),
       Example("I hope to become more organized and declutter my living space.", "Goal"), 
       Example("I'm working on improving my self-confidence and self-esteem.", "Goal"), 
       Example("I want to travel to iconic landmarks and natural wonders around the world.", "Goal"), 
       Example("I aim to achieve a specific financial milestone, such as saving a certain amount for retirement.", "Goal"), 
       Example("I wish to build a personal brand and online presence.", "Goal"), 
       Example("I dream of starting a family and providing a loving home for my children.", "Goal"), 
       Example("I'm committed to volunteering for a cause I deeply care about.", "Goal"), 
       Example("I plan to learn to cook and prepare delicious meals from scratch.", "Goal"), 
       Example("I aspire to become a better problem solver and critical thinker.", "Goal"), 
       Example("I aim to become a more patient and understanding person.", "Goal"), 
       Example("I hope to build a strong and loving relationship with my significant other.", "Goal"), 
       Example("I'm determined to achieve a better work-life-health balance.", "Goal"), 
       Example("I want to explore new hobbies and interests.", "Goal"), 
       Example("I aim to overcome a specific fear or phobia.", "Goal"), 
       Example("I wish to develop a regular exercise routine and stay physically active.", "Goal"), 
       Example("I dream of buying a home in a specific neighborhood or city.", "Goal"), 
       Example("I'm committed to pursuing higher education and personal growth.", "Goal"), 
       Example("I plan to adopt a healthier diet and make nutritious food choices.", "Goal"), 
       Example("I aspire to become a published author or blogger.", "Goal"), 
       Example("I aim to become more financially literate and make wise investments.", "Goal"), 
       Example("I hope to build a successful and fulfilling career in my chosen field.", "Goal"), 
       Example("I'm determined to mend broken relationships and reconnect with loved ones.", "Goal"),
       Example("I want to explore my spirituality and develop a sense of inner peace.", "Goal"), 
       Example("I aim to achieve a specific weight loss or fitness goal.", "Goal"), 
       Example("I wish to travel to historical sites and cultural landmarks.", "Goal"), 
       Example("I dream of starting my own business and being my own boss.", "Goal"), 
       Example("I'm committed to exploring my heritage and family history.", "Goal"), 
       Example("I plan to learn a new form of self-defense or martial art.", "Goal"), 
       Example("I aspire to become a mentor to someone in need of guidance.", "Goal"), 
       Example("I aim to improve my financial stability and emergency fund.", "Goal"), 
       Example("I hope to achieve a sense of inner happiness and contentment in my life.", "Goal"),
Example("Do they truly understand me?", "Relationship"), 
Example("Are we growing together or apart?", "Relationship"),
Example("What are their long-term goals for our relationship?", "Relationship"), 
Example("How does Emily perceive our communication?", "Relationship"),
 Example("Do we share the same values and beliefs?", "Relationship"), 
 Example("Is David happy in our relationship?", "Relationship"), 
 Example("What are Emma's fears or insecurities in this relationship?", "Relationship"), 
 Example("Does James feel appreciated and valued?", "Relationship"), 
 Example("What are Olivia's expectations from me?", "Relationship"),
Example("How does Michael view our level of intimacy?", "Relationship"), 
Example("Are there any unresolved conflicts or issues between us?", "Relationship"), 
Example("What does Sophia think about our future together?", "Relationship"), 
Example("How does Daniel feel about our level of trust?", "Relationship"), 
Example("Do they have concerns about our compatibility?", "Relationship"),
 Example("What are Lily's favorite moments in our relationship?", "Relationship"),
  Example("How does Ethan handle disagreements or arguments?", "Relationship"),
   Example("Is Grace satisfied with our emotional connection?", "Relationship"),
Example("What role does William see me playing in their life?", "Relationship"),
    Example("Does Isabella feel supported in pursuing her dreams?", "Relationship"), 
Example("How does Benjamin perceive our level of independence?", "Relationship"), 
Example("Are they content with our social life and activities?", "Relationship"), 
Example("What is Mia's perspective on our shared responsibilities?", "Relationship"), 
Example("Do they have any unexpressed needs or desires?", "Relationship"), 
Example("How does Christopher view our relationship's balance of power?", "Relationship"), 
Example("Is Ella comfortable with our level of vulnerability?", "Relationship"), 
Example("What does Noah appreciate most about me?", "Relationship"), 
Example("How does Ava handle stress and challenges in our relationship?", "Relationship"), 
Example("Do they have concerns about our commitment?", "Relationship"), 
Example("Is Sophia happy with the frequency of our quality time together?", "Relationship"),
 Example("What are Jackson's thoughts on our level of affection?", "Relationship"), 
 Example("Do they have any worries about our financial situation?", "Relationship"), 
 Example("How does Harper perceive our level of respect for each other?", "Relationship"), 
 Example("Are they comfortable with the pace of our relationship?", "Relationship"), 
 Example("What are Liam's boundaries and expectations regarding privacy?", "Relationship"), 
 Example("Do they have any regrets or past issues they'd like to address?", "Relationship"), 
 Example("How does Zoe envision our relationship evolving in the future?", "Relationship"), 
 Example("Are they satisfied with the balance between giving and receiving?", "Relationship"),
  Example("What are Oliver's thoughts on our ability to compromise?", "Relationship"),
   Example("How does Lily see us managing conflicts in the long term?", "Relationship"), 
   Example("Do they have any concerns about our mutual friendships?", "Relationship"), 
   Example("Is Mia happy with the division of household responsibilities?", "Relationship"),
    Example("How does Elijah feel about our level of emotional support?", "Relationship"),
     Example("Do they have any worries about our commitment to personal growth?", "Relationship"),
      Example("How does Chloe perceive our level of independence?", "Relationship"),
       Example("Are they satisfied with our emotional connection?", "Relationship"),
        Example("What is William's perspective on our shared responsibilities?", "Relationship"),
         Example("Do they have any unexpressed needs or desires?", "Relationship"), 
         Example("How does Grace view our relationship's balance of power?", "Relationship"),
          Example("Are they comfortable with the pace of our relationship?", "Relationship"), 
          Example("What are James's boundaries and expectations regarding privacy?", "Relationship"),
           Example("Do they have any regrets or past issues they'd like to address?", "Relationship"), 
           Example("How does Emily envision our relationship evolving in the future?", "Relationship"), 
           Example("Are they satisfied with the balance between giving and receiving?", "Relationship"), 
           Example("What are Daniel's thoughts on our ability to compromise?", "Relationship"), 
           Example("How does Ava see us managing conflicts in the long term?", "Relationship"),
            Example("Do they have any concerns about our mutual friendships?", "Relationship"),
            Example("Is Benjamin happy with the division of household responsibilities?", "Relationship"), 
Example("How does Olivia feel about our level of emotional support?", "Relationship"),
 Example("Do they have any worries about our commitment to personal growth?", "Relationship"), 
 Example("How does Mia perceive our level of trust?", "Relationship"), 
 Example("Are they comfortable with our level of vulnerability?", "Relationship"), 
 Example("What does William appreciate most about me?", "Relationship"), 
 Example("How does Sophia handle stress and challenges in our relationship?", "Relationship"),
  Example("Do they have concerns about our compatibility?", "Relationship"), 
  Example("What are Emily's favorite moments in our relationship?", "Relationship"), 
Example("How does Daniel handle disagreements or arguments?", "Relationship"),
Example("The gentle rustling of leaves in the breeze on an autumn day.", "Experience"),
 Example("The scent of freshly cut grass on a warm summer afternoon.", "Experience"), 
 Example("The feeling of a raindrop landing softly on your skin.", "Experience"),
  Example("The taste of a sun-ripened tomato picked from the garden.", "Experience"),
  Example("The sound of a babbling brook in the heart of the forest.", "Experience"), 
  Example("The sight of a solitary sailboat gliding across a tranquil lake at sunset.", "Experience"), 
  Example("The texture of cool, wet sand squishing between your toes at the shoreline.", "Experience"), 
  Example("The aroma of cinnamon and cloves wafting from a freshly baked pie.", "Experience"),
   Example("The Experience of a feather-light snowflake landing on your eyelashes.", "Experience"), 
   Example("The sight of a rainbow arching across the sky after a rainstorm.", "Experience"),
    Example("The crisp sound of footsteps on a frost-covered path on a winter morning.", "Experience"), 
    Example("The taste of a sweet, juicy peach dripping with nectar.", "Experience"), 
    Example("The feeling of a gentle hug from a loved one on a tough day.", "Experience"), 
    Example("The scent of old books and weathered pages in a dusty library.", "Experience"), 
    Example("The warmth of a crackling campfire on a chilly night in the woods.", "Experience"), 
    Example("The sound of waves crashing against rugged cliffs along the coast.", "Experience"),
    Example("The sight of a field of wildflowers dancing in the wind.", "Experience"), 
    Example("The texture of velvety petals on a fragrant rose in a garden.", "Experience"), 
    Example("The taste of salty tears mixed with laughter during a heartfelt conversation.", "Experience"), 
    Example("The feeling of soft, warm sand between your fingers as you build a sandcastle.", "Experience"), 
    Example("The aroma of sizzling bacon and freshly brewed coffee in the morning.", "Experience"), 
    Example("The Experience of cool raindrops on your face during a summer downpour.", "Experience"), 
    Example("The sight of a city skyline illuminated by the glow of neon lights at night.", "Experience"), 
    Example("The sound of a crackling bonfire at a beach bonfire party.", "Experience"), 
    Example("The taste of a gooey, melted marshmallow roasted over an open flame.", "Experience"), 
    Example("The feeling of a gentle caress from the sun's rays on a spring day.", "Experience"), 
    Example("The scent of pine needles and earth in a dense, ancient forest.", "Experience"), 
    Example("The Experience of a cool, misty breeze on your face at the edge of a waterfall.", "Experience"), 
    Example("The sight of a lone wolf silhouetted against a full moon in a quiet wilderness.", "Experience"), 
    Example("The texture of fine sandpaper beneath your fingertips as you create art.", "Experience"), 
    Example("The taste of salt on your lips as you float on the surface of the ocean.", "Experience"), 
    Example("The sound of a distant thunderstorm approaching on a hot summer day.", "Experience"), 
    Example("The feeling of soft, damp earth beneath your bare feet in a garden.", "Experience"), 
    Example("The aroma of blooming lilacs and honeysuckle in a hidden garden.", "Experience"), 
    Example("The warmth of a cozy blanket enveloping you on a cold winter's night.", "Experience"), 
    Example("The sight of a vibrant, bustling marketplace filled with colors and flavors.", "Experience"), 
    Example("The sound of a child's laughter echoing through a playground.", "Experience"), 
    Example("The taste of a perfectly ripe mango, its juices dripping down your chin.", "Experience"), 
    Example("The feeling of a cool breeze ruffling your hair on a mountaintop.", "Experience"), 
    Example("The scent of a bakery's freshly baked bread on a quiet morning stroll.", "Experience"), 
    Example("The Experience of a cat's soft purr as it curls up in your lap.", "Experience"), 
    Example("The sight of a rainbow-hued hot air balloon floating gracefully in the sky.", "Experience"), 
    Example("The texture of silky, white sand beneath your toes on a tropical beach.", "Experience"), 
    Example("The taste of a rich, velvety piece of dark chocolate melting in your mouth.", "Experience"), 
    Example("The sound of leaves crunching beneath your boots on a woodland hike.", "Experience"), 
    Example("The aroma of blooming lavender fields stretching as far as the eye can see.", "Experience"), 
    Example("The warmth of a crackling fireplace on a chilly winter evening.", "Experience"), 
    Example("The sight of a field of fireflies lighting up the night in a magical display.", "Experience"), 
    Example("The feeling of a warm, welcoming hug from an old friend you haven't seen in years.", "Experience"), 
    Example("The taste of a tangy, sun-ripened orange bursting with juice.", "Experience"), 
    Example("The sound of a distant waterfall hidden deep within a lush, green forest.", "Experience"), 
    Example("The Experience of a gentle rain shower washing away the cares of the day.", "Experience"), 
    Example("The sight of a vast desert landscape under a brilliant, star-studded night sky.", "Experience"), 
    Example("The texture of soft, powdery snow beneath your skis on a snowy slope.", "Experience"), 
    Example("The scent of blooming roses and fresh-cut grass in a spring garden.", "Experience"), 
    Example("The taste of a warm, flaky croissant paired with a cup of strong espresso.", "Experience"),
     Example("The sound of waves gently lapping against the side of a boat on a tranquil lake.", "Experience"), 
     Example("The feeling of a loved one's hand in yours as you watch a breathtaking sunset.", "Experience"), 
     Example("The aroma of smoky barbecue drifting from a summer cookout in the park.", "Experience"), 
     Example("The warmth of a soft, cozy sweater wrapped around you on a cool autumn day.", "Experience"), 
     Example("The sight of a full moon casting a silvery glow on a serene, midnight sea.", "Experience"), 
     Example("The Experience of cool, refreshing water cascading over your skin in a waterfall.", "Experience"), 
     Example("The taste of a perfectly ripe, sweet strawberry picked from a sun-drenched field.", "Experience"), 
     Example("The sound of leaves rustling in a gentle forest breeze on a tranquil afternoon.", "Experience"), 
     Example("The scent of freshly fallen rain on the warm pavement after a summer storm.", "Experience"), 
     Example("The feeling of soft, powdery sand between your toes as you walk along the shore.", "Experience"), 
     Example("The sight of a field of sunflowers stretching toward the sun in a golden sea.", "Experience"), 
     Example("The texture of fine, soft fur beneath your fingertips as you stroke a beloved pet.", "Experience"), 
     Example("The taste of a warm, buttery croissant on a leisurely morning in a Parisian cafe.", "Experience"), 
     Example("The sound of gentle, rhythmic waves lulling you into a peaceful, seaside slumber.", "Experience"), 
     Example("The feeling of a loved one's embrace, their heartbeat syncing with yours in perfect harmony.", "Experience"), 
     Example("The aroma of freshly ground coffee beans brewing in the morning, filling the air with anticipation.", "Experience"),
     Example("Complete the report for the upcoming meeting.", "Todo"),
Example("Buy groceries for the week.", "Todo"),
Example("Schedule a dentist appointment.", "Todo"),
Example("Pay the monthly rent or mortgage.", "Todo"),
Example("Set up a meeting with the project team.", "Todo"),
Example("Clean the garage and organize tools.", "Todo"),
Example("Call the plumber to fix the leaky faucet.", "Todo"),
Example("Submit the job application online.", "Todo"),
Example("Write thank-you notes for gifts received.", "Todo"),
Example("I wish I could travel the world and explore new cultures.", "Goal"),
Example("I wish I had more time to spend with my family.", "Goal"),
Example("I wish I could speak multiple languages fluently.", "Goal"),
Example("I wish I had the courage to pursue my dream career.", "Goal"),
Example("I wish I could make a positive impact on the environment.", "Goal"),
Example("I wish I could master a musical instrument.", "Goal"),
Example("I wish I had more opportunities to volunteer and give back to my community.", "Goal"),
Example("I wish I could write a book and share my stories with the world.", "Goal"),
Example("I wish I could travel back in time and relive certain moments in my life.", "Goal"),
Example("I wish I had more financial stability and could save for the future.", "Goal"),
Example("I wish I could overcome my fear of public speaking.", "Goal"),
Example("I wish I could improve my physical fitness and lead a healthier lifestyle.", "Goal"),
Example("I wish I had more patience in dealing with difficult situations.", "Goal"),
Example("I wish I could spend more time in nature and disconnect from technology.", "Goal"),
Example("I wish I had the skills to start my own business.", "Goal"),
Example("I wish I could learn to cook gourmet meals.", "Goal"),
Example("I wish I had the opportunity to travel to space.", "Goal"),
Example("I wish I could meet my favorite celebrity or role model.", "Goal"),
Example("I wish I could develop a deeper sense of inner peace and mindfulness.", "Goal"),
Example("I wish I had the ability to help those in need and make a difference in their lives.", "Goal"),
Example("Create a budget for next month.", "Todo"),
Example("Pick up dry cleaning on the way home.", "Todo"),
Example("Send birthday cards to friends and family.", "Todo"),
Example("Research vacation destinations for the summer.", "Todo"),
Example("Renew the car registration and insurance.", "Todo"),
Example("Organize and declutter the home office.", "Todo"),
Example("Book flights for the upcoming business trip.", "Todo"),
Example("Prepare a grocery list for the dinner party.", "Todo"),
Example("Install new software updates on the computer.", "Todo"),
Example("Buy a gift for a friend's wedding.", "Todo"),
Example("Sort through old clothes and donate unused items.", "Todo"),
Example("Water the plants in the garden.", "Todo"),
Example("Schedule a checkup with the doctor.", "Todo"),
Example("Pick up a prescription from the pharmacy.", "Todo"),
Example("Send out invitations for the event.", "Todo"),
Example("Research and choose a new phone plan.", "Todo"),
Example("Review and respond to work emails.", "Todo"),
Example("Set up a home security system appointment.", "Todo"),
Example("Call a family member to catch up.", "Todo"),
Example("Buy school supplies for the kids.", "Todo"),
Example("Clean out the refrigerator and dispose of expired items.", "Todo"),
Example("Prepare a list of discussion topics for the team meeting.", "Todo"),
Example("Send important documents to the client.", "Todo"),
Example("Register for a cooking class.", "Todo"),
Example("Complete online training courses for professional development.", "Goal"),
Example("Set up automatic bill payments.", "Todo"),
Example("Schedule a yoga or fitness class.", "Todo"),
Example("Plan a weekend getaway with a loved one.", "Todo"),
Example("Fix the broken step on the front porch.", "Todo"),
Example("Pick up a book from the library.", "Todo"),
Example("Call a friend to schedule a catch-up lunch.", "Todo"),
Example("Prepare a list of household repairs and maintenance tasks.", "Todo"),
Example("Set a reminder for a family member's birthday.", "Todo"),
Example("Buy tickets for a concert or event.", "Todo"),
Example("Check the tire pressure and oil level in the car.", "Todo"),
Example("Prepare and file taxes before the deadline.", "Todo"),
Example("Organize a charity event or volunteer day.", "Goal"),
Example("Review and update the resume.", "Todo"),
Example("Plan a surprise party for a loved one.", "Todo"),
Example("Schedule a regular checkup for the pet at the veterinarian.", "Todo"),
Example("Prepare a list of goals and priorities for the month.", "Todo"),
Example("Start a home improvement project.", "Todo"),
Example("Purchase new school uniforms for the kids.", "Todo"),
Example("Set up a recurring donation to a favorite charity.", "Todo"),
Example("Review and revise a business plan.", "Todo"),
Example("Clean the gutters and downspouts.", "Todo"),
Example("Schedule a date night with a significant other.", "Todo"),
Example("Create a weekly meal plan and grocery list.", "Todo"),
Example("Call the cable provider to adjust the subscription.", "Todo"),
Example("Research and book a family vacation.", "Todo"),
Example("Set up a meeting with a financial advisor.", "Todo"),
Example("Buy a new book to read during leisure time.", "Todo"),
Example("Prepare a list of home maintenance tasks for each season.", "Todo"),
Example("Sort and organize digital files and photos.", "Todo"),
Example("Schedule a home energy audit.", "Todo"),
Example("Plan a surprise visit to a friend or family member.", "Todo"),
Example("Research and compare car insurance quotes.", "Todo"),
Example("Set up a regular exercise routine.", "Todo"),
Example("Create a list of potential New Year's resolutions.", "Todo"),
Example("Check and update the smoke detectors in the house.", "Todo"),
Example("Schedule a haircut or salon appointment.", "Todo"),
Example("Buy a gift for a child's birthday party.", "Todo"),
Example("Prepare a list of career goals and aspirations.", "Todo"),
Example("Review and update the emergency contact list.", "Todo"),
Example("Set a reminder to change the air filter in the HVAC system.", "Todo"),
Example("Plan and host a themed dinner party with friends.", "Todo"),
Example("Buy a new piece of exercise equipment or gear.", "Todo"),
Example("Schedule a yearly checkup and maintenance for the car.", "Todo"),
Example("Prepare a list of potential vacation destinations for the year.", "Todo"),
Example("Set up a regular time to call or visit elderly family members.", "Todo"),
Example("Check and replenish the first aid kit supplies.", "Todo"),
Example("Feeling overwhelmed with work and deadlines.", "Experience"),
Example("Traffic was terrible this morning; I was stuck for hours.", "Experience"),
Example("I can't seem to shake this feeling of loneliness.", "Experience"),
Example("My neighbor's loud music is keeping me up at night.", "Experience"),
Example("I'm constantly tired, and I don't know why.", "Experience"),
Example("It's been raining for days, and I'm tired of the gloomy weather.", "Experience"),
Example("I'm frustrated with my lack of progress in my fitness goals.", "Experience"),
Example("I had an argument with a close friend today.", "Experience"),
Example("I'm worried about my financial situation; bills keep piling up.", "Experience"),
Example("I miss my family, and it's been so long since we last met.", "Experience"),
Example("My allergies are acting up again, and it's making me miserable.", "Experience"),
Example("I can't believe I forgot an important appointment today.", "Experience"),
Example("Work is so stressful lately; I need a break.", "Experience"),
Example("I feel like I'm stuck in a rut, doing the same things every day.", "Experience"),
Example("I'm upset about the news and all the negativity in the world.", "Experience"),
Example("I'm frustrated with my slow internet connection.", "Experience"),
Example("I have so much clutter in my home; it's overwhelming.", "Experience"),
Example("I made a mistake at work, and I can't stop thinking about it.", "Experience"),
Example("I wish I had more time for my hobbies and passions.", "Experience"),
Example("I'm annoyed with the constant noise from construction nearby.", "Experience"),
Example("I can't find my keys, and I'm running late.", "Experience"),
Example("I'm feeling unappreciated in my relationship.", "Experience"),
Example("I had a terrible headache all day.", "Experience"),
Example("I'm frustrated with my lack of progress in my studies.", "Experience"),
Example("I got caught in the rain without an umbrella.", "Experience"),
Example("I'm exhausted from dealing with difficult customers at work.", "Experience"),
Example("I had a disagreement with a family member.", "Experience"),
Example("I'm upset about the state of the environment.", "Experience"),
Example("I'm annoyed with the constant notifications on my phone.", "Experience"),
Example("I feel like I'm constantly juggling too many responsibilities.", "Experience"),
Example("I'm disappointed with the service I received at a restaurant.", "Experience"),
Example("I'm tired of the constant noise in the city.", "Experience"),
Example("I have a never-ending to-do list, and it's stressing me out.", "Experience"),
Example("I'm frustrated with my lack of free time.", "Experience"),
Example("I had a bad night's sleep, and I'm so groggy today.", "Experience"),
Example("I'm worried about a pending medical test result.", "Experience"),
Example("I'm annoyed with my coworker's constant interruptions.", "Experience"),
Example("I'm upset about a recent breakup.", "Experience"),
Example("I feel like I'm always running out of time.", "Experience"),
Example("I'm overwhelmed by all the social obligations I have.", "Experience"),
Example("I'm frustrated with my slow progress in a personal project.", "Experience"),
Example("I had a terrible commute to work today.", "Experience"),
Example("I'm annoyed with the constant ads on the internet.", "Experience"),
Example("I'm worried about the health of a family member.", "Experience"),
Example("I'm tired of my noisy neighbors upstairs.", "Experience"),
Example("I'm disappointed with the quality of a product I purchased.", "Experience"),
Example("I feel like I'm always comparing myself to others.", "Experience"),
Example("I'm frustrated with the lack of communication at my workplace.", "Experience"),
Example("I had a frustrating experience with customer service.", "Experience"),
Example("I'm annoyed with the never-ending political debates.", "Experience"),
Example("I'm tired of being stuck in traffic during rush hour.", "Experience"),
Example("I'm overwhelmed by the constant stream of emails in my inbox.", "Experience"),
Example("I'm upset about a friend canceling plans at the last minute.", "Experience"),
Example("I'm frustrated with my inability to find a parking spot.", "Experience"),
Example("I'm disappointed with the outcome of a recent event.", "Experience"),
Example("I'm annoyed with the noise from a nearby construction site.", "Experience"),
Example("I'm worried about the safety of my neighborhood.", "Experience"),
Example("I'm tired of feeling pressured to keep up with social media.", "Experience"),
Example("I'm overwhelmed by the clutter in my digital workspace.", "Experience"),
Example("I'm frustrated with the constant stream of notifications on my phone.", "Experience"),
Example("I'm upset about a recent argument with my partner.", "Experience"),
Example("I'm disappointed with the customer service at a store.", "Experience"),
Example("I feel like I'm always rushing from one task to another.", "Experience"),
Example("I'm annoyed with the noise pollution in the city.", "Experience"),
Example("I'm worried about the state of the economy.", "Experience"),
Example("I'm tired of the constant pressure to be productive.", "Experience"),
Example("I'm overwhelmed by the number of meetings at work.", "Experience"),
Example("I'm frustrated with my inability to focus and concentrate.", "Experience"),
Example("I'm upset about a misunderstanding with a friend.", "Experience"),
Example("I'm disappointed with the lack of support from a colleague.", "Experience"),
Example("I feel like I'm always stuck in a traffic jam.", "Experience"),
Example("I'm annoyed with the noise from a nearby construction project.", "Experience"),
Example("I'm worried about the impact of climate change.", "Experience"),
Example("I'm tired of the constant pressure to meet deadlines.", "Experience"),
Example("I'm overwhelmed by the expectations placed on me.", "Experience"),
Example("I'm frustrated with the lack of appreciation at work.", "Experience"),
Example("I can't believe how lucky I am to have Sarah in my life.", "Relationship"),
Example("John always knows how to make me laugh, no matter how bad my day has been.", "Relationship"),
Example("Amanda is such a kind and compassionate person.", "Relationship"),
Example("I had the most amazing conversation with David today.", "Relationship"),
Example("Emily and I have been through so much together, and our bond just keeps getting stronger.", "Relationship"),
Example("I'm so grateful for the support and love that Mark gives me every day.", "Relationship"),
Example("Maria is the most reliable person I know.", "Relationship"),
Example("Alex is like a brother to me; we share everything.", "Relationship"),
Example("I trust Jennifer with my deepest secrets.", "Relationship"),
Example("Lucas and I have so many inside jokes; it's like we have our own language.", "Relationship"),
Example("I admire how hardworking and dedicated Sarah is.", "Relationship"),
Example("I can always count on Michael to have my back.", "Relationship"),
Example("Katie's smile brightens up my day.", "Relationship"),
Example("I feel like I've known Daniel my whole life.", "Relationship"),
Example("Stephanie and I share a bond that can't be broken.", "Relationship"),
Example("Sarah told me she feels ecstatic about her upcoming wedding.", "Relationship"),
Example("John told me he feels anxious before taking his final exams.", "Relationship"),
Example("Emily told me she feels overwhelmed by the responsibilities at work.", "Relationship"),
Example("David told me he feels lonely since moving to a new city.", "Relationship"),
Example("Michael told me he feels proud of his recent promotion.", "Relationship"),
Example("Maria told me she feels inspired after attending an art exhibition.", "Relationship"),
Example("Alex told me he feels grateful for his supportive friends.", "Relationship"),
Example("Alex feels grateful for his supportive friends.", "Relationship"),
Example("Jennifer feels excited about her upcoming travel adventure.", "Relationship"),
Example("Lucas feels devastated after the loss of his pet.", "Relationship"),
Example("Katie feels thrilled to be accepted into her dream college.", "Relationship"),
Example("Daniel feels nostalgic when he listens to his favorite childhood song.", "Relationship"),
Example("Stephanie feels confident about her upcoming job interview.", "Relationship"),
Example("Thomas feels content with his life in the countryside.", "Relationship"),
Example("Laura feels frustrated with her daily commute.", "Relationship"),
Example("Chris feels relieved after resolving a long-standing conflict.", "Relationship"),
Example("Hannah feels curious about exploring new hobbies.", "Relationship"),
Example("Robert feels exhausted after a long day of work.", "Relationship"),
Example("Mark feels surprised by his unexpected success.", "Relationship"),
Example("Jennifer feels peaceful when meditating by the ocean.", "Relationship"),
Example("Lucas feels hopeful about his future career prospects.", "Relationship"),
Example("Thomas told me he feels content with his life in the countryside.", "Relationship"),
Example("Laura told me she feels frustrated with her daily commute.", "Relationship"),
Example("Chris told me he feels relieved after resolving a long-standing conflict.", "Relationship"),
Example("Hannah told me she feels curious about exploring new hobbies.", "Relationship"),
Example("Robert told me he feels exhausted after a long day of work.", "Relationship"),
Example("Mark told me he feels surprised by his unexpected success.", "Relationship"),
Example("Jennifer told me she feels peaceful when meditating by the ocean.", "Relationship"),
Example("Lucas told me he feels hopeful about his future career prospects.", "Relationship"),
Example("My son is so tired.", "Relationship"),
Example("Parsa works so hard.", "Relationship"),
Example("I cherish the moments I spend with Thomas.", "Relationship"),
Example("Laura has a heart of gold.", "Relationship"),
Example("No one understands me quite like Chris.", "Relationship"),
Example("My mom has a kidney stone", "Relationship"),
Example("Carrie has serious migranes.", "Relationship"),
Example("She works so hard!", "Relationship"),
Example("He gets these terrible strokes.", "Relationship"),
Example("Hannah is the sister I never had.", "Relationship"),
Example("I can always rely on Robert for a good conversation.", "Relationship"),
Example("I love how adventurous and spontaneous Sarah is.", "Relationship"),
Example("Mark's sense of humor is one of a kind.", "Relationship"),
Example("Maria's generosity knows no bounds.", "Relationship"),
Example("I can be myself completely around Alex.", "Relationship"),
Example("Jennifer's wisdom always guides me in the right direction.", "Relationship"),
Example("Lucas and I share a deep connection that transcends words.", "Relationship"),
Example("I'm inspired by Sarah's creativity.", "Relationship"),
Example("Michael's loyalty is unmatched.", "Relationship"),
Example("Katie has a heart of gold.", "Relationship"),
Example("Daniel and I have a unique bond that I cherish.", "Relationship"),
Example("Stephanie and I have weathered many storms together.", "Relationship"),
Example("Thomas always knows how to make me feel better.", "Relationship"),
Example("I admire Laura's strength and resilience.", "Relationship"),
Example("Chris is my confidant, and I value our conversations deeply.", "Relationship"),
Example("Hannah and I share a bond that goes beyond friendship.", "Relationship"),
Example("Robert and I have a connection that's hard to find.", "Relationship"),
Example("Sarah's adventurous spirit inspires me.", "Relationship"),
Example("Mark's humor brightens even the darkest days.", "Relationship"),
Example("Maria's generosity knows no bounds.", "Relationship"),
Example("Alex is like family to me.", "Relationship"),
Example("Jennifer's wisdom is a guiding light in my life.", "Relationship"),
Example("Lucas and I have a connection that words can't express.", "Relationship"),
Example("I'm constantly amazed by Sarah's creativity.", "Relationship"),
Example("Michael's loyalty and support mean the world to me.", "Relationship"),
Example("Katie's kindness and compassion are unmatched.", "Relationship"),
Example("Daniel and I share a bond that's unbreakable.", "Relationship"),
Example("Stephanie is my rock, and I'm grateful for her every day.", "Relationship"),
Example("Thomas's presence in my life is a blessing.", "Relationship"),
Example("Laura's strength inspires me to be a better person.", "Relationship"),
Example("Chris and I share a connection that's hard to put into words.", "Relationship"),
Example("Hannah is like a sister to me, and I wouldn't have it any other way.", "Relationship"),
Example("Robert and I have a deep understanding that I cherish.", "Relationship"),
Example("Sarah's adventurous spirit is infectious.", "Relationship"),
Example("Mark's humor is a ray of sunshine on cloudy days.", "Relationship"),
Example("Maria's generosity is boundless, and I'm lucky to know her.", "Relationship"),
Example("Alex is my rock, and I trust him completely.", "Relationship"),
Example("Jennifer's wisdom has guided me through many tough times.", "Relationship"),
Example("Lucas and I share a connection that transcends words.", "Relationship"),
Example("I'm constantly inspired by Sarah's creative talents.", "Relationship"),
Example("Michael's loyalty and support mean the world to me.", "Relationship"),
Example("Katie's kindness and compassion are a source of strength.", "Relationship"),
Example("Daniel and I share a bond that's deeper than words can express.", "Relationship"),
Example("Stephanie is my confidant, and I'm grateful for her every day.", "Relationship"),
Example("Thomas's presence in my life is a constant reminder of how blessed I am.", "Relationship"),
Example("Laura's strength and resilience inspire me to be a better person.", "Relationship"),
Example("Chris and I share a connection that goes beyond words.", "Relationship"),
Example("Hannah is like a sister to me, and I'm grateful for her friendship.", "Relationship"),
Example("Robert and I have a deep and meaningful connection that I treasure.", "Relationship"),
Example("Sarah's adventurous spirit is contagious, and I love exploring new experiences with her.", "Relationship"),
Example("Mark's sense of humor never fails to brighten my day.", "Relationship"),
Example("Maria's generosity knows no bounds, and I'm fortunate to have her in my life.", "Relationship"),
Example("Alex is not just a friend; he's family, and I value our bond immensely.", "Relationship"),
Example("Jennifer's wisdom has been a guiding light in my life, helping me make important decisions.", "Relationship"),
Example("Lucas and I share a connection that words can't capture; it's a deep and profound understanding.", "Relationship"),
Example("I'm continually inspired by Sarah's creative talents and her ability to see beauty in the world.", "Relationship"),
Example("Michael's loyalty and unwavering support are qualities I cherish in our relationship.", "Relationship"),
Example("Katie's kindness and compassion are sources of strength and comfort in my life.", "Relationship"),
Example("Daniel and I share a bond that goes beyond words; it's a connection of the heart.", "Relationship"),
Example("Stephanie is my confidant, and her presence in my life is a constant source of comfort.", "Relationship"),
Example("Thomas's presence in my life is a blessing, and I'm grateful for the joy he brings.", "Relationship"),
Example("Laura's strength and resilience inspire me to face life's challenges with courage.", "Relationship"),
Example("Chris and I share a connection that transcends ordinary friendships; it's something truly special.", "Relationship"),
Example("Hannah is like a sister to me, and her friendship is a treasured part of my life.", "Relationship"),
Example("Robert and I have a deep and meaningful connection that I hold dear.", "Relationship"),
Example("Sarah's adventurous spirit is contagious, and I'm grateful for the adventures we share.", "Relationship")
]

semexamples = [
Example("Alex is always so supportive and kind", "Positive"),
Example("Sarah has an incredible sense of humor", "Positive"),
Example("David is a true leader and inspires others", "Positive"),
Example("Emma is a great listener and offers valuable advice", "Positive"),
Example("Olivia's positivity is infectious", "Positive"),
Example("Liam is incredibly talented and hardworking", "Positive"),
Example("Ava's generosity knows no bounds", "Positive"),
Example("Jackson's determination is truly admirable", "Positive"),
Example("Sophia has a heart of gold", "Positive"),
Example("Mason's creativity knows no limits", "Positive"),
Example("Isabella's intelligence is unmatched", "Positive"),
Example("William is always there when you need him", "Positive"),
Example("Ella's smile can brighten anyone's day", "Positive"),
Example("James is a role model for us all", "Positive"),
Example("Grace's kindness towards animals is inspiring", "Positive"),
Example("Benjamin's patience is legendary", "Positive"),
Example("Chloe's dedication to her goals is commendable", "Positive"),
Example("Lucas's optimism is truly uplifting", "Positive"),
Example("Lily's passion for learning is contagious", "Positive"),
Example("Aiden's sense of humor is second to none", "Positive"),
Example("I'm not sure why they even want to hang out with me", "Negative"),
Example("I always feel like I'm the least interesting person in the group", "Negative"),
Example("They're so amazing, and I'm just here", "Negative"),
Example("I don't know why they put up with my negativity", "Negative"),
Example("I'm constantly worried they'll realize I'm not good enough for them", "Negative"),
Example("I feel like I burden them with my problems", "Negative"),
Example("I can't believe they still talk to me after all my mistakes", "Negative"),
Example("I dwell on past mistakes and never forgive myself", "Negative"),
Example("I avoid setting any goals or aspirations for my future", "Negative"),
Example("I constantly seek validation and approval from others", "Negative"),
Example("I avoid any form of exercise or physical activity", "Negative"),
Example("I maintain a cluttered and disorganized living space", "Negative"),
Example("I neglect my hobbies and interests that bring me joy", "Negative"),
Example("I engage in toxic or abusive relationships", "Negative"),
Example("I overspend and accumulate debt to keep up with others", "Negative"),
Example("I obsessively focus on my flaws and insecurities", "Negative"),
Example("I avoid seeking professional help for my mental health concerns", "Negative"),
Example("I'm grateful for the breathtaking beauty of a colorful sunrise", "Positive"),
Example("I appreciate the soothing sound of rain on a quiet afternoon", "Positive"),
Example("I'm thankful for the vibrant colors of autumn leaves", "Positive"),
Example("I feel gratitude for the refreshing scent of pine trees in a forest", "Positive"),
Example("Today, I woke up at 7:00 AM.", "Neutral"),
Example("I made a to-do list for tomorrow.", "Neutral"),
Example("I received an email from my coworker about a meeting next week.", "Neutral"),
Example("I did some online shopping and ordered a new pair of shoes.", "Neutral"),
Example("I cleaned the kitchen and did the dishes.", "Neutral"),
Example("I listened to a podcast while doing household chores.", "Neutral"),
Example("I wrote a letter to my grandmother.", "Neutral"),
Example("I watered the plants on the balcony.", "Neutral"),
Example("I took a hot shower before bed.", "Neutral"),
Example("I organized my closet and donated some clothes.", "Neutral"),
Example("I practiced a few new chords on my guitar.", "Positive"),
Example("I did some meditation to relax before sleep.", "Positive"),
Example("I updated my budget spreadsheet for the month.", "Neutral"),
Example("I was running late all day, and then ended up missing a lecture.", "Negative"),
Example("The weather really sucked today.", "Negative"),
Example("I went to bed around 11:00 PM.", "Neutral"),
Example("I cried all day.", "Negative"),
Example("I had pains and cramps", "Negative"),
Example("My aunt died. I'm in mourning. I haven't been able to sleep.", "Negative"),
Example("I'm overwhelmed and not sure how to cope.", "Negative"),
Example("Everything is working out really well", "Positive"),
Example("I need to start coming to class early.", "Neutral"),
Example("I need to stop smoking.", "Neutral"),
Example("I'm so excited for the next steps in my life.", "Positive")
]



class CategorizeNotes(Resource):
    """Categorize notes using Cohere API.
       Notes are annotated with a field 'category'.
       These are: 'To-do', 'Experience', 'Relationship', 'Goal'
    """
    def post(self):
        notes = request.json['notes']
        # Placeholder for Cohere API call to categorize notes
        categorized_notes = {}  # Replace with Cohere API result
        return jsonify(categorized_notes)
    def catty(note):
        string = note["content"]
        delimiters = ['?', '.', '!']
        result = [string]
        for delimiter in delimiters: 
            temp_result = []
            for item in result:
                if item != '':
                    temp_result.extend(item.split(delimiter))
            result = temp_result
        responseIntention = co.classify(model='large', inputs=result, examples=examples)
        responseEmotion = co.classify(model='large', inputs=result, examples=semexamples)
        rl = len(result) ##this is how many results there are
        emotionSum = 0;
        for r in range (0, rl):
            if responseEmotion[r] == "Positive":
                emotionSum+=1
            if responseEmotion[r] == "Negative":
                emotionSum-=1
            if responseIntention[r] == "Goal":
                goalCount+=1
            if responseIntention[r] == "Experience":
                experienceCount+=1
            if responseIntention[r] == "Relationship":
                relationshipCount+=1
            if responseIntention[r] == "Todo":
                todoCount+=1
        if emotionSum > 1:
            note["sentiment"] = "Positive"
        elif emotionSum < -1:
            note["sentiment"] = "Negative"
        else:
            note["sentiment"] = "Neutral"
        l = [goalCount, experienceCount, relationshipCount, todoCount]
        ind1 = l.index(max(l))
        t = []
        del l[ind1]
        ind2 = l.index(max(l))
        if ind1 == 0 or ind2 == 0:
            t.append("Goal")
        if ind1 == 1 or ind2 == 1:
            t.append("Experience")
        if ind1 == 2 or ind2 == 2:
            t.append("Relationship")
        if ind1 == 3 or ind2 == 3:
            t.append("Todo")
        note["Types"] = t
        return note